### ISSUE TITLE
Should have Yarn and GitHub packages support.

### ISSUE THREAD

**Issue by TheAwesomeCoder05** [TheAwesomeCoder05/MusicComp-v2#10]
Just to make this more accessible, this project should also be published to other package managers in the near future.

**Comment by TheAwesomeCoder05** [comment]
Forgot to update, but Yarn Support complete.

**Comment by TheAwesomeCoder05** [comment]
GitHub packages on hold for time being considering lack of demand. Closing this issue for now.

**Comment by CompeyDev** [comment]
GitHub Package support is finally here!
