### ISSUE TITLE
Update dependencies to work with latest versions

### ISSUE THREAD

**Issue by TheAwesomeCoder05** [TheAwesomeCoder05/MusicComp-v2#9]
Currently, a lot of the dependencies' latest versions break the project, so have to update stuff and make them compatible with the latest versions. In the future the `--legacy-peer-deps` parameter shouldn't be needed.

**Comment by TheAwesomeCoder05** [comment]
Almost fixed, some testing required and this will be part of MusicComp v0.2.13 and v0.2.14.

**Comment by CompeyDev** [comment]
Update has now been rolled out.
